name: 'Spin plugin releaser'
description: 'Set up your GitHub Actions workflow with a specific version of spin'
author: 'Fermyon Engineering'
inputs:
  template_file:
    required: false
    description: 'the plugin template file'
  upload_checksums:
    required: false
    description: 'if enabled, uploads a checksums-<tagname>.txt file to release'
  upload_plugin_manifest:
    required: false
    default: true
    description: 'if enabled, uploads the rendered plugin manifest file to release'
  github_token:
    required: false
    description: 'github token used for downloading artifacts to render template'
  release_webhook_url:
    required: false
    description: 'The release webhook url to use instead of using the default'
runs:
  using: 'node20'
  main: 'dist/index.js'
